### ISSUE TITLE
Connecting with QGroundcontrol/APMPlaner not working

### ISSUE THREAD

**Issue by lfrodrigues** [DrTon/jMAVSim#1]
I'm trying to connect qgroundcontrol with jMAVSim as specified in  
http://pixhawk.org/dev/hil/jmavsim but clicking on the connect button does not work.

Also tried with APMPlaner and has the same problem.

**Comment by killerlayup** [comment]
I have the same issue, can someone help me?
@lfrodrigues  @DrTon  @julianoes  @gitter-badger

**Comment by julianoes** [comment]
@killerlayup This is a very old issue. If it still persists for you, please open a new issue and add some detailed information.
