### ISSUE TITLE
Making jMAVsmi SITL simulator (instead of HITL)

### ISSUE THREAD

**Issue by arjamizo** [DrTon/jMAVSim#21]
How much work is actually needed to change it into fully-working SITL for Pixhawk (or ArduPilotMega?)

I am really looking forward finding an alternative for heavy Gazeboo simulator.

What do you think needs to be done and what are barriers?

**Comment by DrTon** [comment]
It's very easy and I already tried this. I also think that @LorenzMeier and his tam made something with PX4. All you need is just to use UDP instead of serial link to connect to autopilot software. If it uses not mavlink but something else, then you will need some more work, but still possible.
