### ISSUE TITLE
Rotor.setTimeConstant arithmetic looks wrong

### ISSUE THREAD

**Issue by kd0aij** [DrTon/jMAVSim#23]
it looks like rc should be 1/tau but it is set to 1/(2 pi tau)
Also, tau = 5msec seems far too small a delay to model realistic ESC/motor/prop impulse response.

**Comment by DrTon** [comment]
Yes, you are right, fixed. Thanks! What about 5ms, it's just "some value that works". Do you have any measurements as reference?
Closing this, please open new issue once you have realistic and working defaults.
