### ISSUE TITLE
WARNING: Got heartbeat from system #2 but configured to only accept messages from system #1. Please change the system ID parameter to match in order to use HITL/SITL.

### ISSUE THREAD

**Issue by killerlayup** [DrTon/jMAVSim#31]
Hi,
I have an issue when I start jMAVSim to communicate with px4 by running:

    java -Djava.ext.dirs= -cp lib/*:out/production/jmavsim.jar me.drton.jmavsim.Simulator -serial /dev/ttyACM0 921600 -qgc

it shows the blow log:

    WARNING: Got heartbeat from system #2 but configured to only accept messages from system #1. Please change the system ID parameter to match in order to use HITL/SITL.

is that related to MAV_SYS_ID?

**Comment by DrTon** [comment]
I think yes.

**Comment by 1ee7** [comment]
Do you resolved？ I have meeted the same problem?

**Comment by 1ee7** [comment]
How did you resolved? I meet the same problem

**Comment by Thomas10111** [comment]
In file MAVLinkHILSystem.java you have to add "" around sysId (2 times)

else if (!gotHeartBeat && sysId != msg.getInt("sysId")) {
                System.out.println("WARNING: Got heartbeat from system #" + Integer.toString(msg.getInt("sysId")) +
                    " but configured to only accept messages from system #" + Integer.toString(sysId) +
                    ". Please change the system ID parameter to match in order to use HITL/SITL.");

Then compile by calling "ant" again.
