### ISSUE TITLE
Run JmavSim in HITL Mode

### ISSUE THREAD

**Issue by anujkumargupta** [DrTon/jMAVSim#38]
I am trying to run Jmavsim in HITL mode. I follwed the link
https://pixhawk.org/dev/hil/jmavsim
and used /dev/ttyACM0(Pixhawk connected through usb(serial)) and /dev/ttyUSB0(Pixhawk connected through radio telemetry(udp)) and as mention in link ttyusbmodem1 but every time it throws serial port exception either port not found or port busy.

Thanks.

**Comment by DrTon** [comment]
Hi! This repo is not maintained anymore, ask in PX4/jMAVSim please.

**Comment by anujkumargupta** [comment]
thanks
